# Generated by Django 6.0.4 on 2026-04-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
    ]
