# Generated by Django 6.0.4 on 2026-04-24 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_admin', '0002_remove_adminlog_user_delete_systemsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.FloatField(verbose_name='عرض جغرافیایی')),
                ('longitude', models.FloatField(verbose_name='طول جغرافیایی')),
                ('land_use', models.CharField(blank=True, max_length=100, verbose_name='کاربری اراضی')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='مساحت (متر مربع)')),
                ('owner_name', models.CharField(blank=True, max_length=200, verbose_name='نام مالک')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='features/')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.CreateModel(
            name='FeatureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='feature_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core_admin.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core_admin.project'),
        ),
    ]
