# Generated by Django 6.0.4 on 2026-04-26 08:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0004_alter_feature_options_feature_review_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='longitude',
        ),
        migrations.AddField(
            model_name='feature',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='موقعیت مکانی'),
        ),
    ]
