# Generated by Django 6.0.4 on 2026-04-26 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0005_remove_feature_latitude_remove_feature_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='شماره شناسنامه')),
                ('personal_code', models.CharField(blank=True, max_length=20, verbose_name='شماره پرسنلی')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='operator_profiles/', verbose_name='عکس پروفایل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
