# Generated by Django 6.0.4 on 2026-04-27 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0006_operatorprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureattachment',
            options={'verbose_name': 'ضمیمه قطعه', 'verbose_name_plural': 'ضمیمه\u200cهای قطعه'},
        ),
        migrations.AlterModelOptions(
            name='operatorprofile',
            options={'verbose_name': 'پروفایل اپراتور', 'verbose_name_plural': 'پروفایل اپراتورها'},
        ),
        migrations.CreateModel(
            name='JameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('zone_type', models.CharField(max_length=100, verbose_name='نوع پهنه')),
                ('green_percent', models.FloatField(verbose_name='درصد فضای سبز')),
                ('service_centers', models.TextField(verbose_name='مراکز خدماتی نزدیک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jame_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داده طرح جامع',
                'verbose_name_plural': 'داده\u200cهای طرح جامع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MowzoueiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پروژه')),
                ('description', models.TextField(verbose_name='توضیحات تکمیلی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mowzouei_files/', verbose_name='فایل پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mowzouei_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داده طرح موضوعی',
                'verbose_name_plural': 'داده\u200cهای طرح موضوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TafsiliData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('zone_code', models.CharField(max_length=50, verbose_name='کد منطقه')),
                ('detailed_use', models.TextField(verbose_name='کاربری تفصیلی')),
                ('density', models.FloatField(verbose_name='تراکم ساختمانی')),
                ('floor_limit', models.IntegerField(verbose_name='حداکثر طبقات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داده طرح تفصیلی',
                'verbose_name_plural': 'داده\u200cهای طرح تفصیلی',
                'ordering': ['-created_at'],
            },
        ),
    ]
