# Generated by Django 6.0.4 on 2026-04-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0007_alter_featureattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsilidata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tafsili_photos/', verbose_name='عکس طرح'),
        ),
    ]
