# Generated by Django 6.0.4 on 2026-04-27 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0008_tafsilidata_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MomayeziData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع پروژه')),
                ('description', models.TextField(verbose_name='توضیحات تکمیلی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='momayezi_files/', verbose_name='فایل پیوست')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momayezi_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'داده طرح موضوعی',
                'verbose_name_plural': 'داده\u200cهای طرح موضوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MowzoueiData',
        ),
    ]
