# Generated by Django 6.0.4 on 2026-04-28 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0009_momayezidata_delete_mowzoueidata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('tafsili', 'طرح تفصیلی'), ('jame', 'طرح جامع'), ('momayezi', 'ممیزی املاک')], max_length=20, verbose_name='نوع طرح')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('revised', 'نیاز به اصلاح')], default='pending', max_length=20)),
                ('expert_note', models.TextField(blank=True, verbose_name='نظر کارشناس')),
                ('revision_count', models.IntegerField(default=0, verbose_name='تعداد دفعات اصلاح')),
                ('is_final', models.BooleanField(default=False, verbose_name='ثبت نهایی در دیتابیس')),
                ('final_data', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای نهایی')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plans', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_plans', to=settings.AUTH_USER_MODEL, verbose_name='اپراتور')),
            ],
            options={
                'verbose_name': 'طرح پروژه',
                'verbose_name_plural': 'طرح\u200cهای پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(verbose_name='شماره اصلاح')),
                ('operator_data', models.JSONField(default=dict, verbose_name='داده\u200cهای ارسالی اپراتور')),
                ('expert_note', models.TextField(verbose_name='نظر کارشناس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core_admin.projectplan')),
            ],
            options={
                'verbose_name': 'تاریخچه اصلاح طرح',
                'verbose_name_plural': 'تاریخچه اصلاحات طرح\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MomayeziPlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_code', models.CharField(max_length=50, verbose_name='کد پلاک')),
                ('ownership_type', models.CharField(choices=[('private', 'خصوصی'), ('public', 'دولتی'), ('endowment', 'وقف'), ('joint', 'مشاع')], max_length=50, verbose_name='نوع مالکیت')),
                ('owner_name', models.CharField(max_length=200, verbose_name='نام مالک')),
                ('building_type', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('office', 'اداری'), ('industrial', 'صنعتی'), ('mixed', 'مختلط')], max_length=50, verbose_name='نوع بنا')),
                ('area', models.FloatField(verbose_name='مساحت (متر مربع)')),
                ('construction_year', models.IntegerField(verbose_name='سال ساخت')),
                ('is_licensed', models.BooleanField(default=False, verbose_name='دارای پروانه ساخت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='momayezi_plans/', verbose_name='فایل پیوست')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='momayezi_plan', to='core_admin.projectplan')),
            ],
        ),
        migrations.CreateModel(
            name='JamePlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('agricultural', 'کشاورزی'), ('industrial', 'صنعتی'), ('mixed', 'مختلط')], max_length=50, verbose_name='نوع پهنه')),
                ('green_percent', models.FloatField(verbose_name='درصد فضای سبز')),
                ('service_centers', models.TextField(verbose_name='مراکز خدماتی نزدیک')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jame_plan', to='core_admin.projectplan')),
            ],
        ),
        migrations.CreateModel(
            name='TafsiliPlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=50, verbose_name='کد منطقه')),
                ('land_use_type', models.CharField(max_length=100, verbose_name='نوع کاربری اراضی')),
                ('detailed_use', models.TextField(verbose_name='کاربری تفصیلی')),
                ('density', models.FloatField(verbose_name='تراکم ساختمانی')),
                ('floor_limit', models.IntegerField(verbose_name='حداکثر طبقات مجاز')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tafsili_plans/', verbose_name='عکس طرح')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tafsili_plan', to='core_admin.projectplan')),
            ],
        ),
    ]
