# Generated by Django 6.0.4 on 2026-04-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0010_projectplan_planrevisionhistory_momayeziplandata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalJameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(max_length=50, verbose_name='نوع پهنه')),
                ('green_percent', models.FloatField(verbose_name='درصد فضای سبز')),
                ('service_centers', models.TextField(verbose_name='مراکز خدماتی نزدیک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_jame', to='core_admin.projectplan')),
            ],
            options={
                'verbose_name': 'داده نهایی طرح جامع',
                'verbose_name_plural': 'داده\u200cهای نهایی طرح جامع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalMomayeziData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_code', models.CharField(max_length=50, verbose_name='کد پلاک')),
                ('ownership_type', models.CharField(max_length=50, verbose_name='نوع مالکیت')),
                ('owner_name', models.CharField(max_length=200, verbose_name='نام مالک')),
                ('building_type', models.CharField(max_length=50, verbose_name='نوع بنا')),
                ('area', models.FloatField(verbose_name='مساحت (متر مربع)')),
                ('construction_year', models.IntegerField(verbose_name='سال ساخت')),
                ('is_licensed', models.BooleanField(default=False, verbose_name='دارای پروانه ساخت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='final/momayezi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_momayezi', to='core_admin.projectplan')),
            ],
            options={
                'verbose_name': 'داده نهایی ممیزی املاک',
                'verbose_name_plural': 'داده\u200cهای نهایی ممیزی املاک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalTafsiliData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(max_length=50, verbose_name='کد منطقه')),
                ('land_use_type', models.CharField(max_length=100, verbose_name='نوع کاربری اراضی')),
                ('detailed_use', models.TextField(verbose_name='کاربری تفصیلی')),
                ('density', models.FloatField(verbose_name='تراکم ساختمانی')),
                ('floor_limit', models.IntegerField(verbose_name='حداکثر طبقات مجاز')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='final/tafsili/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_tafsili', to='core_admin.projectplan')),
            ],
            options={
                'verbose_name': 'داده نهایی طرح تفصیلی',
                'verbose_name_plural': 'داده\u200cهای نهایی طرح تفصیلی',
                'ordering': ['-created_at'],
            },
        ),
    ]
