# Generated by Django 6.0.4 on 2026-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0011_finaljamedata_finalmomayezidata_finaltafsilidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tafsiliplandata',
            name='additional_desc',
            field=models.TextField(blank=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='building_age',
            field=models.CharField(blank=True, max_length=20, verbose_name='قدمت بنا'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, verbose_name='کیفیت ابنیه'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='built_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت اعیانی'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, verbose_name='انواع کاربری (غالب)'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نما'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='سطح عملکردی'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, verbose_name='کاربری همکف'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت عرصه'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='مصالح ساختمانی'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام محله'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='occupancy_level',
            field=models.FloatField(blank=True, null=True, verbose_name='سطح اشغال'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع مالکیت'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد، شناسه'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام معبر'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض معبر'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, verbose_name='کاربری طبقات بالای همکف'),
        ),
        migrations.DeleteModel(
            name='TafsiliData',
        ),
    ]
