# Generated by Django 6.0.4 on 2026-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0012_tafsiliplandata_additional_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tafsiliplandata',
            name='additional_desc',
        ),
        migrations.RemoveField(
            model_name='tafsiliplandata',
            name='occupancy_level',
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قدمت بنا'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کیفیت ابنیه'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='انواع کاربری (غالب)'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع نما'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سطح عملکردی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری همکف'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مصالح ساختمانی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محله'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پلاک'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tafsili_plans/'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام معبر'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری طبقات بالای همکف'),
        ),
    ]
