# Generated by Django 6.0.4 on 2026-04-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0013_remove_tafsiliplandata_additional_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='تراکم ساختمانی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='detailed_use',
            field=models.TextField(blank=True, null=True, verbose_name='کاربری تفصیلی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='floor_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر طبقات مجاز'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='land_use_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کاربری اراضی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tafsili_plans/', verbose_name='عکس طرح'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد منطقه'),
        ),
    ]
