# Generated by Django 6.0.4 on 2026-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0014_alter_tafsiliplandata_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='built_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='detailed_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='floor_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='land_use_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tafsili_plans/'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='street_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
