# Generated by Django 6.0.4 on 2026-04-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0015_alter_tafsiliplandata_building_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltafsilidata',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قدمت بنا'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کیفیت ابنیه'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='built_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت اعیانی'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='انواع کاربری (غالب)'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع نما'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سطح عملکردی'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری همکف'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت عرصه'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مصالح ساختمانی'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محله'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مالکیت'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پلاک'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام معبر'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض معبر'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری طبقات بالای همکف'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='تراکم ساختمانی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='detailed_use',
            field=models.TextField(blank=True, null=True, verbose_name='کاربری تفصیلی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='floor_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر طبقات مجاز'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='land_use_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کاربری اراضی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد منطقه'),
        ),
    ]
