# Generated by Django 6.0.4 on 2026-05-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0016_finaltafsilidata_building_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finaljamedata',
            options={'verbose_name': 'داده نهایی طرح جامع', 'verbose_name_plural': 'داده\u200cهای نهایی طرح جامع'},
        ),
        migrations.AlterModelOptions(
            name='finaltafsilidata',
            options={'verbose_name': 'داده نهایی طرح تفصیلی', 'verbose_name_plural': 'داده\u200cهای نهایی طرح تفصیلی'},
        ),
        migrations.AlterField(
            model_name='finaljamedata',
            name='green_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaljamedata',
            name='service_centers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaljamedata',
            name='zone_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='built_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='detailed_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='floor_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='land_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='land_use_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='street_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
