# Generated by Django 6.0.4 on 2026-05-05 18:40

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0018_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamedata',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='jameplandata',
            name='plan',
        ),
        migrations.AlterModelOptions(
            name='finaltafsilidata',
            options={},
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='building_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت ساخت'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='موقعیت مکانی'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='finaltafsilidata',
            name='occupancy_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='سطح اشغال (%)'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='building_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت ساخت'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='floor_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد طبقات'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='موقعیت مکانی'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='occupancy_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='سطح اشغال (%)'),
        ),
        migrations.AddField(
            model_name='tafsiliplandata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قدمت بنا'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کیفیت ابنیه'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='built_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت اعیانی (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='تراکم ساختمانی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='detailed_use',
            field=models.TextField(blank=True, null=True, verbose_name='کاربری تفصیلی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='انواع کاربری (غالب)'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع نما'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='floor_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر طبقات'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سطح عملکردی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری همکف'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت عرصه (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='land_use_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کاربری اراضی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='material_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مصالح ساختمانی'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محله'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پلاک'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='final_tafsili/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام معبر'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض معبر (متر)'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری طبقات بالای همکف'),
        ),
        migrations.AlterField(
            model_name='finaltafsilidata',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد منطقه'),
        ),
        migrations.AlterField(
            model_name='projectplan',
            name='plan_type',
            field=models.CharField(choices=[('tafsili', 'طرح تفصیلی / جامع'), ('momayezi', 'ممیزی املاک')], max_length=20, verbose_name='نوع طرح'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='building_age',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قدمت بنا'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='building_quality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کیفیت ابنیه'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='built_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت اعیانی (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='تراکم ساختمانی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='detailed_use',
            field=models.TextField(blank=True, null=True, verbose_name='کاربری تفصیلی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='dominant_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='انواع کاربری (غالب)'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='facade_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع نما'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='floor_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='حداکثر طبقات مجاز'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='functional_level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='سطح عملکردی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='ground_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری همکف'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='land_area',
            field=models.FloatField(blank=True, null=True, verbose_name='مساحت عرصه (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='land_use_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع کاربری اراضی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مصالح ساختمانی'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام محله'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='ownership_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='parcel_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد شناسه قطعه'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tafsili_plans/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام معبر'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض معبر (متر)'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='upper_floor_use',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربری طبقات بالای همکف'),
        ),
        migrations.AlterField(
            model_name='tafsiliplandata',
            name='zone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد منطقه'),
        ),
        migrations.DeleteModel(
            name='FinalJameData',
        ),
        migrations.DeleteModel(
            name='JameData',
        ),
        migrations.DeleteModel(
            name='JamePlanData',
        ),
    ]
