# Generated by Django 6.0.4 on 2026-05-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_admin', '0019_remove_jamedata_operator_remove_jameplandata_plan_and_more'),
    ]

    operations = [
    ]
